//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Sorak.Model
{
    public partial class Question
    {
        public Question()
        {
            this.LikeCount = 0;
            this.VotingUsers = new HashSet<User>();
        }
    
        public int RecordNum { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> InstanceId { get; set; }
        public int OwnerUserId { get; set; }
        public int OwnerSubjectId { get; set; }
        public int LikeCount { get; set; }
    
        public virtual User OwnerUser { get; set; }
        public virtual ICollection<User> VotingUsers { get; set; }
        public virtual Subject OwnerSubject { get; set; }
    }
    
}
