//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Sorak.Model
{
    public partial class Subject
    {
        public Subject()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int RecordNum { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> InstanceId { get; set; }
        public string EventDate { get; set; }
        public int QuestionCount { get; set; }
        public string StatusCode { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
    
}
