//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Sorak.Model
{
    public partial class User
    {
        public User()
        {
            this.AskedQuestions = new HashSet<Question>();
            this.VotedQuestions = new HashSet<Question>();
        }
    
        public int RecordNum { get; set; }
        public string EmailAddress { get; set; }
        public string WindowsUsername { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    
        public virtual ICollection<Question> AskedQuestions { get; set; }
        public virtual ICollection<Question> VotedQuestions { get; set; }
    }
    
}
